#define UNICODE
#define _UNICODE
#include <winsock2.h>
#include <ws2tcpip.h>
#include <windows.h>
#include <windowsx.h>
#include <commctrl.h>
#include <gdiplus.h>
#include <shellapi.h>
#include <string>
#include <vector>
#include <fstream>
#include <sstream>
#include <thread>
#include <mutex>
#include <filesystem>
#include <memory>
#include <atomic>
#pragma comment(lib,"gdiplus.lib")
#pragma comment(lib,"ws2_32.lib")
using namespace Gdiplus;
struct Note { std::wstring text; std::wstring modified; };
static HWND gWnd,gList,gEdit; static std::vector<Note> gNotes; static int gSelected=0; static bool gDetail=false; static ULONG_PTR gGdi; static std::thread gServer; static std::atomic_bool gServing=false; static unsigned short gPort=0; static std::mutex gMutex;
static std::wstring root(){ wchar_t p[MAX_PATH]; GetModuleFileNameW(nullptr,p,MAX_PATH); return std::filesystem::path(p).parent_path().wstring(); }
static std::wstring dataFile(){ wchar_t p[MAX_PATH]; GetEnvironmentVariableW(L"LOCALAPPDATA",p,MAX_PATH); return std::wstring(p)+L"\\HelloIPAWindowsNative-notes.txt"; }
static std::wstring now(){ SYSTEMTIME t;GetLocalTime(&t); wchar_t b[64];swprintf_s(b,L"%04d-%02d-%02d %02d:%02d",t.wYear,t.wMonth,t.wDay,t.wHour,t.wMinute);return b; }
static std::wstring title(const Note& n){ auto p=n.text.find_first_of(L"\r\n"); auto s=n.text.substr(0,p); if(s.empty())return L"新备忘录"; return s; }
static void save(){ std::wofstream f{std::filesystem::path(dataFile())}; for(auto&n:gNotes){std::wstring s=n.text;for(auto&c:s)if(c==L'\n')c=L'\v';f<<n.modified<<L"\t"<<s<<L"\n";} }
static void load(){ std::wifstream f{std::filesystem::path(dataFile())};std::wstring line;while(std::getline(f,line)){auto p=line.find(L'\t');if(p==std::wstring::npos)continue;Note n{line.substr(p+1),line.substr(0,p)};for(auto&c:n.text)if(c==L'\v')c=L'\n';gNotes.push_back(n);}if(gNotes.empty())gNotes.push_back({L"欢迎使用 HelloIPA Windows 版\n",now()}); }
static Image* image(const wchar_t* n){return Image::FromFile((root()+L"\\assets\\"+n).c_str());}
static void drawImage(HDC dc,const wchar_t*n,RECT r){std::unique_ptr<Image> im(image(n));if(im&&im->GetLastStatus()==Ok){Graphics g(dc);g.DrawImage(im.get(),(INT)r.left,(INT)r.top,(INT)(r.right-r.left),(INT)(r.bottom-r.top));}}
static void layout(){RECT r;GetClientRect(gWnd,&r);int w=r.right; if(gDetail){ShowWindow(gList,SW_HIDE);SetWindowPos(gEdit,nullptr,34,118,w-68,r.bottom-220,SWP_NOZORDER);}
else{ShowWindow(gEdit,SW_HIDE);SetWindowPos(gList,nullptr,0,72,w,r.bottom-72,SWP_NOZORDER);ShowWindow(gList,SW_SHOW);} InvalidateRect(gWnd,nullptr,FALSE);}
static void refreshList(){SendMessageW(gList,LB_RESETCONTENT,0,0);for(auto&n:gNotes)SendMessageW(gList,LB_ADDSTRING,0,(LPARAM)title(n).c_str());SendMessageW(gList,LB_SETCURSEL,gSelected,0);}
static void showDetail(int i){if(i<0||i>=(int)gNotes.size())return;gSelected=i;gDetail=true;SetWindowTextW(gEdit,gNotes[i].text.c_str());layout();}
static void showList(){if(gDetail){int len=GetWindowTextLengthW(gEdit);std::wstring s(len,L'\0');GetWindowTextW(gEdit,s.data(),len+1);gNotes[gSelected].text=s;gNotes[gSelected].modified=now();save();}gDetail=false;refreshList();layout();}
static void createNote(){gNotes.insert(gNotes.begin(),{L"",now()});gSelected=0;showDetail(0);save();}
static void deleteNote(){if(gNotes.size()>1)gNotes.erase(gNotes.begin()+gSelected);else gNotes[0]={L"",now()};if(gSelected>=(int)gNotes.size())gSelected=(int)gNotes.size()-1;showDetail(gSelected);save();}
static std::string utf8(const std::wstring&s){if(s.empty())return{};int n=WideCharToMultiByte(CP_UTF8,0,s.data(),(int)s.size(),nullptr,0,nullptr,nullptr);std::string o(n,0);WideCharToMultiByte(CP_UTF8,0,s.data(),(int)s.size(),o.data(),n,nullptr,nullptr);return o;}
static std::wstring wide(const std::string&s){int n=MultiByteToWideChar(CP_UTF8,0,s.data(),(int)s.size(),nullptr,0);std::wstring o(n,0);MultiByteToWideChar(CP_UTF8,0,s.data(),(int)s.size(),o.data(),n);return o;}
static void startServer(){if(gServing)return;WSADATA wd;WSAStartup(MAKEWORD(2,2),&wd);SOCKET s=socket(AF_INET,SOCK_STREAM,IPPROTO_TCP);sockaddr_in a{};a.sin_family=AF_INET;a.sin_addr.s_addr=INADDR_ANY;a.sin_port=0;bind(s,(sockaddr*)&a,sizeof(a));listen(s,4);int z=sizeof(a);getsockname(s,(sockaddr*)&a,&z);gPort=ntohs(a.sin_port);gServing=true;gServer=std::thread([s](){while(gServing){SOCKET c=accept(s,nullptr,nullptr);if(c==INVALID_SOCKET)break;char buf[65536];int n=recv(c,buf,sizeof(buf)-1,0);if(n>0){buf[n]=0;std::string req(buf);if(req.rfind("POST /sync",0)==0){auto p=req.find("\r\n\r\n");if(p!=std::string::npos){std::string body=req.substr(p+4);auto q=body.find("\"text\"");if(q!=std::string::npos){q=body.find(':',q);auto b=body.find('"',q);auto e=body.find_last_of('"');if(b!=std::string::npos&&e>b){std::wstring v=wide(body.substr(b+1,e-b-1));std::lock_guard<std::mutex>lk(gMutex);gNotes[gSelected].text=v;gNotes[gSelected].modified=now();save();}}}std::string out="HTTP/1.1 204 No Content\r\n\r\n";send(c,out.c_str(),(int)out.size(),0);}else{std::lock_guard<std::mutex>lk(gMutex);std::string body="<meta charset='utf-8'><h2>HelloIPA 共享文本</h2><form method='post' action='/sync'><textarea name='text' style='width:90%;height:300px'>"+utf8(gNotes[gSelected].text)+"</textarea><br><button>同步到电脑</button></form>";std::string out="HTTP/1.1 200 OK\r\nContent-Type: text/html; charset=utf-8\r\nContent-Length: "+std::to_string(body.size())+"\r\n\r\n"+body;send(c,out.c_str(),(int)out.size(),0);}}closesocket(c);}closesocket(s);});}
static void share(){startServer();std::wstring msg=L"请在同一 Wi‑Fi 的电脑浏览器打开：\nhttp://127.0.0.1:"+std::to_wstring(gPort)+L"\n\n跨设备访问时请将 127.0.0.1 替换为本机局域网 IPv4 地址。";MessageBoxW(gWnd,msg.c_str(),L"共享地址",MB_OK|MB_ICONINFORMATION);}
static LRESULT CALLBACK proc(HWND h,UINT m,WPARAM w,LPARAM l){switch(m){case WM_CREATE:{gWnd=h;gList=CreateWindowW(L"LISTBOX",nullptr,WS_CHILD|WS_VISIBLE|LBS_OWNERDRAWFIXED|LBS_HASSTRINGS|WS_VSCROLL,0,72,1,1,h,(HMENU)10,GetModuleHandleW(nullptr),nullptr);gEdit=CreateWindowW(L"EDIT",nullptr,WS_CHILD|ES_MULTILINE|ES_AUTOVSCROLL|WS_VSCROLL|WS_BORDER,0,0,1,1,h,(HMENU)11,GetModuleHandleW(nullptr),nullptr);SendMessageW(gEdit,WM_SETFONT,(WPARAM)GetStockObject(DEFAULT_GUI_FONT),TRUE);refreshList();layout();break;}case WM_SIZE:layout();break;case WM_COMMAND:if(HIWORD(w)==LBN_DBLCLK&&LOWORD(w)==10)showDetail((int)SendMessageW(gList,LB_GETCURSEL,0,0));else if(LOWORD(w)==100)showList();else if(LOWORD(w)==101)createNote();else if(LOWORD(w)==102)deleteNote();else if(LOWORD(w)==103)share();else if(LOWORD(w)==104&&gSelected>0)showDetail(gSelected-1);else if(LOWORD(w)==105&&gSelected+1<(int)gNotes.size())showDetail(gSelected+1);break;case WM_MEASUREITEM:return TRUE;case WM_DRAWITEM:{auto*d=(DRAWITEMSTRUCT*)l;if(d->CtlID==10){FillRect(d->hDC,&d->rcItem,(HBRUSH)(COLOR_WINDOW+1));if(d->itemID<(UINT)gNotes.size()){SetTextColor(d->hDC,RGB(63,38,27));SetBkMode(d->hDC,TRANSPARENT);TextOutW(d->hDC,d->rcItem.left+18,d->rcItem.top+12,title(gNotes[d->itemID]).c_str(),(int)title(gNotes[d->itemID]).size());MoveToEx(d->hDC,d->rcItem.left,d->rcItem.bottom-1,nullptr);LineTo(d->hDC,d->rcItem.right,d->rcItem.bottom-1);}}return TRUE;}case WM_PAINT:{PAINTSTRUCT ps;HDC dc=BeginPaint(h,&ps);RECT r;GetClientRect(h,&r);drawImage(dc,L"oldos-notes-body.png",{0,72,r.right,r.bottom});drawImage(dc,L"oldos-notes-topbar.png",{0,0,r.right,72});SetBkMode(dc,TRANSPARENT);SetTextColor(dc,RGB(255,255,255));HFONT f=CreateFontW(28,0,0,0,FW_BOLD,0,0,0,DEFAULT_CHARSET,0,0,0,0,L"Segoe UI");SelectObject(dc,f);std::wstring head=gDetail?title(gNotes[gSelected]):L"Notes ("+std::to_wstring(gNotes.size())+L")";if(gDetail&&head.size()>8)head=head.substr(0,8)+L"…";TextOutW(dc,r.right/2-(int)head.size()*8,21,head.c_str(),(int)head.size());DeleteObject(f);if(!gDetail){TextOutW(dc,r.right-55,20,L"+",1);}else{TextOutW(dc,18,22,L"Notes",5);TextOutW(dc,r.right-55,20,L"+",1);TextOutW(dc,18,r.bottom-66,L"‹",1);TextOutW(dc,r.right-38,r.bottom-66,L"›",1);TextOutW(dc,r.right/2-20,r.bottom-66,L"Wi-Fi",5);TextOutW(dc,r.right/2+35,r.bottom-66,L"删除",2);}EndPaint(h,&ps);break;}case WM_LBUTTONUP:{POINT p{GET_X_LPARAM(l),GET_Y_LPARAM(l)};RECT r;GetClientRect(h,&r);if(p.y<72&&p.x>r.right-90)createNote();else if(gDetail&&p.y<72&&p.x<90)showList();else if(gDetail&&p.y>r.bottom-100){if(p.x<80&&gSelected>0)showDetail(gSelected-1);else if(p.x>r.right-80&&gSelected+1<(int)gNotes.size())showDetail(gSelected+1);else if(p.x>r.right/2+5&&p.x<r.right/2+100)deleteNote();else if(p.x>r.right/2-80&&p.x<r.right/2)share();}break;}case WM_DESTROY:PostQuitMessage(0);break;}return DefWindowProcW(h,m,w,l);}
int WINAPI wWinMain(HINSTANCE hi,HINSTANCE, PWSTR,int cmd){GdiplusStartupInput in;GdiplusStartup(&gGdi,&in,nullptr);load();WNDCLASSW wc{};wc.hInstance=hi;wc.lpfnWndProc=proc;wc.lpszClassName=L"HelloIPAWindowsNative";wc.hCursor=LoadCursor(nullptr,IDC_ARROW);wc.hbrBackground=(HBRUSH)(COLOR_WINDOW+1);RegisterClassW(&wc);gWnd=CreateWindowW(wc.lpszClassName,L"HelloIPA Windows",WS_OVERLAPPEDWINDOW|WS_CLIPCHILDREN,CW_USEDEFAULT,CW_USEDEFAULT,460,820,nullptr,nullptr,hi,nullptr);ShowWindow(gWnd,cmd);UpdateWindow(gWnd);MSG msg;while(GetMessageW(&msg,nullptr,0,0)){TranslateMessage(&msg);DispatchMessageW(&msg);}GdiplusShutdown(gGdi);return 0;}
