const state={notes:[],selected:0,screen:'list',shareURL:null};
const $=s=>document.querySelector(s); const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const titleOf=n=>{const t=(n.text||'').split(/\r?\n/)[0].trim();return t||'新备忘录'};
const dateOf=n=>new Date(n.modifiedAt).toLocaleDateString('en-US',{month:'numeric',day:'numeric',year:'2-digit'});
const persist=()=>window.helloIPA.saveNotes(state.notes);
function topbar(title,back=false){return `<header class="topbar">${back?'<button class="back" data-action="list">Notes</button>':''}<span>${esc(title)}</span><button data-action="new">＋</button></header>`}
function listView(){return `<section class="screen">${topbar(`Notes (${state.notes.length})`)}<div class="paper"><div class="list">${state.notes.map((n,i)=>`<button class="row" data-select="${i}"><span class="title">${esc(titleOf(n))}</span><span class="date">${dateOf(n)}</span><span class="chevron">›</span></button>`).join('')}</div></div></section>`}
function editorView(n){const canPrev=state.selected>0,canNext=state.selected<state.notes.length-1;const t=titleOf(n);return `<section class="screen editor">${topbar(t.length>8?Array.from(t).slice(0,8).join('')+'…':t,true)}<div class="paper"><div class="meta"><span>Today</span><span>${new Date(n.modifiedAt).toLocaleDateString('en-US',{month:'short',day:'numeric'})} ${new Date(n.modifiedAt).toLocaleTimeString('en-US',{hour:'2-digit',minute:'2-digit',hour12:false})}</span></div><textarea id="editor" spellcheck="false">${esc(n.text||'')}</textarea><nav class="toolbar"><button data-action="prev" ${canPrev?'':'disabled'}>‹</button><button data-action="share">⌁</button><button data-action="delete"><img src="assets/oldos-notes-trash.png"></button><button data-action="next" ${canNext?'':'disabled'}>›</button></nav></div></section>`}
function render(){state.selected=Math.min(state.selected,state.notes.length-1);$('#app').innerHTML=state.screen==='list'?listView():editorView(state.notes[state.selected])}
function showToast(text){const el=document.createElement('div');el.className='toast';el.textContent=text;document.body.append(el);setTimeout(()=>el.remove(),1500)}
function showShare(){ $('#app').insertAdjacentHTML('beforeend',`<div class="modal" id="share"><div class="modal-card">${topbar('共享地址')}<div class="content"><p>请让电脑和手机连接同一个 Wi‑Fi，然后在浏览器打开下面这个地址：</p><div class="url">${esc(state.shareURL)}</div><div class="modal-actions"><button data-action="copy">复制这个地址</button><button data-action="close-share">关闭</button></div><p>电脑打开后会看到当前这段文本内容。</p></div></div></div>`)}
document.addEventListener('click',async e=>{const a=e.target.closest('[data-action]')?.dataset.action;const select=e.target.closest('[data-select]');if(select){state.selected=+select.dataset.select;state.screen='editor';render();return}if(!a)return;if(a==='list'){state.screen='list';render()}if(a==='new'){state.notes.unshift({id:crypto.randomUUID(),text:'',modifiedAt:new Date().toISOString()});state.selected=0;state.screen='editor';await persist();render()}if(a==='prev'&&state.selected>0){state.selected--;render()}if(a==='next'&&state.selected<state.notes.length-1){state.selected++;render()}if(a==='delete'){state.notes.splice(state.selected,1);if(!state.notes.length)state.notes=[{id:crypto.randomUUID(),text:'',modifiedAt:new Date().toISOString()}];state.selected=Math.min(state.selected,state.notes.length-1);await persist();render()}if(a==='share'){state.shareURL=await window.helloIPA.startShare(state.notes[state.selected].id);showShare()}if(a==='copy'){await window.helloIPA.copy(state.shareURL);showToast('已复制')}if(a==='close-share'){await window.helloIPA.stopShare();$('#share')?.remove();state.shareURL=null}});
document.addEventListener('input',e=>{if(e.target.id!=='editor')return;const n=state.notes[state.selected];n.text=e.target.value;n.modifiedAt=new Date().toISOString();persist()});
window.helloIPA.onNotesUpdated(notes=>{state.notes=notes;render()});
(async()=>{state.notes=await window.helloIPA.getNotes();render()})();
